### PR TITLE
Move layout manager to context

### PR DESCRIPTION
**Pull request by FostUK**
Plus:
* Fix screen templates
* Make carousel buttons stick to 4/3 screen
* Add gel vanilla assets

Note:
This could be further cleaned up if we move scaler and potentially the accessibility manager to gel as they might be the only things the need them. For further discussion.

### CODE REVIEW

**Comment by SeanHolden** [comment]
Looks good to me!

**Comment by timmydd** [comment]
# Testing
1. Dev Theme: Crash on pause screen. Errors with...
Cannot read property 'keyLookup' of undefined
2.  Worst Witch Theme: Lines on some of the bottoms of the buttons.
3. All Star Racing Theme: On load, Errors are seen in the console.

**Comment by FostUK** [comment]
@timmydd - thanks for checking this. Have fixed 2 and 3 but we are leaving 1 until the new pause screen is merged.

**Comment by FolaOlakunbi** [comment]
@FostUK 
1. Dev theme still crashing on load.
2. Worst Witch Theme: Lines no longer appearing on the button.s
3. All Star Racing Theme: Errors no longer in console.

**Pull request merged**
